version: '3.7'
services:
  postgres:
    container_name: postgres_graphql
    image: postgres
    environment:
      - POSTGRES_USER=aninda
      - POSTGRES_PASSWORD=aninda
      - POSTGRES_DB=graphql
    volumes:
      - postgresgraphql:/var/lib/postgresql/data
      - ./db/initsql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    # networks:
    #   - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_graphql
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-graphql@test.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-graphql}
      - PGADMIN_SERVER_JSON_FILE=/servers.json
    volumes:
        -  pgadmingraphql:/var/lib/pgadmin:rw
        # - ./db/initsql:/var/lib/pgadmin/storage/tapup_shell.com:rw
        - ./db/servers.json:/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # networks:
    #   - postgres
    restart: unless-stopped
    depends_on: 
      - postgres

  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'

  author:
    depends_on: 
      - postgres
      - pgadmin
    image: author-service
    build:
      context: ./author-service/
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001
    volumes:
      - /usr/src/app/node_modules
      - ./author-service:/usr/src/app
    restart: on-failure:10

  genre:
    depends_on:
      - postgres
      - pgadmin
    image: genre-service
    build:
      context: ./genre-service/
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 4002:4002
    volumes:
      - /usr/src/app/node_modules
      - ./genre-service:/usr/src/app
    restart: on-failure:10

  book:
    depends_on:
      - postgres
      - pgadmin
    image: book-service
    build:
      context: ./book-service/
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 4003:4003
    volumes:
      - /usr/src/app/node_modules
      - ./book-service:/usr/src/app
    restart: on-failure:10

  gateway:
    depends_on:
      - postgres
      - pgadmin
      - author
      - genre
    image: gateway-service
    build:
      context: ./gateway-service/
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 4005:4005
    volumes:
      - /usr/src/app/node_modules
      - ./gateway-service:/usr/src/app
    restart: on-failure:10

#  book:
#    depends_on:
#      - postgres
#      - pgadmin
#    image: book-service
#    build:
#      context: ./book-service/
#      dockerfile: Dockerfile.dev
#    environment:
#      NODE_ENV: development
#    ports:
#      - 4003:4003
#    volumes:
#      - /usr/src/app/node_modules
#      - ./book-service:/usr/src/app
#    restart: on-failure:10
volumes:
  postgresgraphql:
  pgadmingraphql: